name: Build C3
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ESP-IDF
        run: |
          git clone --depth 1 --branch v5.5.2 https://github.com/espressif/esp-idf.git /opt/esp/idf
          cd /opt/esp/idf
          ./install.sh esp32c3
      - name: Build
        run: |
          . /opt/esp/idf/export.sh
          echo 'CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y' >> sdkconfig.defaults
          idf.py set-target esp32c3
          idf.py build
          idf.py merge-bin
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/merged-binary.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin
